version: '3.8'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: "!change me!"
      TELEGRAM_BOT_WEBHOOK_SECRET: 123456
    command: sh -c "/usr/bin/supervisord -c  /etc/supervisor/conf.d/worker.conf && composer install --ignore-platform-reqs && php-fpm"
    volumes:
      - ./:/var/www/html
      - ./docker/app/worker.conf:/etc/supervisor/conf.d/worker.conf
    ports:
      - "9000:9000"
    networks:
      - test-app-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
    networks:
      - test-app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - test-app-network

  ngrok:
    image: ngrok/ngrok:latest
    command: "http nginx:80"
    environment:
        NGROK_AUTHTOKEN: 30N6A0D9YCopUvwJopt0cS3JahN_6D9k46zSJdKxT6bexFkaJ
    ports:
      - "4040:4040"
    networks:
          - test-app-network

networks:
  test-app-network:
    driver: bridge

volumes:
  mysql_data:
